export const globalUnit = {
  coupe: ["coupes", "coupe", "cp.", "cp"],
  tasse: ["tasses", "tasse", "tass à café."],
  bol: ["bols", "bol", "bol à soupe."],
  bouteille: ["bouteilles", "bouteille", "btl.", "btl"],
  ounce: ["onces", "once", "oz.", "oz", "oc.", "oc"],
  pinte: ["pintes", "pinte", "pt.", "pt"],
  pound: ["pounds", "pound", "lbs.", "lbs", "lb.", "lb"],
  quart: ["quarts", "quart", "qts.", "qts", "qt.", "qt"],
  cuillereasoupe: [
    "cuilleres a soupe",
    "cuillère à soupe",
    "cuillères à soupe",
    "cuillere a soupe",
    "c.à soupe",
    "c. a soupe",
    "c.à soupe",
    "c.a soupe",
    "c. à soupe",
    "c a soupe",
    "c. a soupe",
    "c. a soupe",
    "c a soupe",
    "cas.",
    "c à s",
    "c a s",
    "c.à s.",
    "cuillere a soupe",
    "tbs.",
    "tbs",
    "T.",
    "T"
  ],
  cuillereacafe: [
    "cuilleres a cafe",
    "cuillere a cafe",
    "cuilleres a cafe",
    "cuillère à cafe",
    "cuillères à cafe",
    "cuillére à cafe",
    "cuilléres à cafe",
    "cuillere a cafe",
    "cuillère a cafe",
    "cuillères a cafe",
    "c.à café",
    "c. a café",
    "c.à café",
    "c.a café",
    "c.a cafe",
    "c.à cafe",
    "c. à café",
    "c. à cafe",
    "c. a café",
    "c. a cafe",
    "c.à c.",
    "cac.",
    "c à c",
    "c a c",
    "cac",
    "c"
  ],
  kg: ["kilogrammes", "kilogramme", "kilos", "kilo", "kg.", "kg"],
  g: ["grammes", "gramme", "gr.", "gr", "g.", "g"],
  l: ["littres", "littre", "lit.", "l.", "l"],
  dcl: ["decilittres", "decilittre", "dclit.", "dcl.", "dl"],
  cl: ["centilitres", "centilitre", "cl.", "cl"],
  mg: ["milligrammes", "milligramme", "mlg.", "mlg", "mg.", "mg"],
  ml: ["millilitres", "millilitre", "mlt", "ml.", "ml"],
  zeste: ["élan", "zeste", "mordant", "elan"],
  poignee: ["poignées", "poignée", "poignée", "poignee", "poignees", "poigne"],
  pincee: ["pincées", "pincée", "pincee", "pincees", "pince"],
  touche: ["touches", "touche"],
  tranche: ["tranches", "tranche"],
  paquet: ["paquets", "paquets"],
  enveloppe: ["enveloppes", "enveloppe"],
  eclat: [
    "éclaboussures",
    "eclaboussures",
    "éclats",
    "éclat",
    "eclat",
    "eclats"
  ],
  brin: ["brins", "brin"],
  feuille: ["feuilles", "feuille"],
  sachet: ["sachets", "sachet"],
  dose: ["doses", "dose"]
};
